baseURL : "https://themewniverse.com"
languageCode : en-us
title : Daddy Trash
enableInlineShortcodes: true
theme: Papermod

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  profileMode:
    enabled: true
    title: Daddy Trash Web
    subtitle: Welcome! I’m Mewniverse, an Artist and Webmaster of this blog. 
    imageUrl: 'https://daddytrash.com/images/PastelDTLogo.png'
    imageTitle: 
    buttons:
      - name: Posts
        url: feed
      - name: Commissions
        url: https://daddytrash.com/commissions
      - name: Shop
        url: https://mewsshop.company.site/

  disqusShortname: Mewniverse 

  socialIcons: 
    - name: patreon
      url: "https://patreon.com/mewniverse"
    - name: bluesky
      url: "https://mewniverse.bsky.social"
    - name: twitter
      url: "https://twitter.com/mewniverse"

  ShowPostNavLinks: true

showToc: false
TocOpen: false
draft: false
canonicalURL: "https://canonical.url/to/page"
disableHLJS: true # to disable highlightjs
disableShare: true
hideSummary: false
searchHidden: false
ShowPostNavLinks: true

hidefooter: true

menu:
  main:
    - identifier: comics
      name: Comics
      url: /comics/
      weight: 10
    - identifier: fiction
      name: Fiction
      url: /fiction/
      weight: 20
    - identifier: rss
      name: RSS
      url: https://daddytrash.com/rssfeed.txt
      weight: 30  
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 40
    - identifier: search
      name: Search
      url: /search/
      weight: 50
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 60
    
privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true